---
- name: SW CONFIG | Install and configure software
  hosts: all
  become: true
  vars:
    backup_vm_ip: 192.168.11.160
    client_vm_ip: 192.168.11.150

  tasks:
    - name: SW CONFIG | Install EPEL Repo package from standart repo
      yum:
        name: epel-release
        state: present
      tags:
        - epel-package
        - packages

    - name: SW CONFIG | Install BORGBACKUP package from EPEL Repo
      yum:
        name: borgbackup
        state: latest
      tags:
        - borg-package
        - packages

    - name: USER CONFIG | Add the user 'borg' 
      user:
        name: borg
        comment: borg backup
      tags:
        - user

    - name: BACKUP CONFIG | Change mode /home/borg/.ssh/
      file:
        path: /home/borg/.ssh
        mode: u=rwx,g-rwx,o-rwx
        state: directory
        owner: borg
        group: borg
      tags:
        - user
        - ssh-config


- name: SSH CONFIG
  hosts: 127.0.0.1
  connection: local
  become: true
  tasks:
    - name: SSH KEYPAIR GENERATION
      openssh_keypair:
        path: /tmp/id_ssh_rsa
        size: 2048
      tags:
        - ssh-config

- name: CLIENT CONFIG
  hosts: client
  become: true
  tasks:
    - name: CLIENT CONFIG | Fill private key
      copy:
        src: /tmp/id_ssh_rsa
        dest: /home/borg/.ssh/id_ssh_rsa
        mode: u=rw,g-rwx,o-rwx
        owner: borg
        group: borg
      tags:
        - ssh-config


- name: BACKUP CONFIG | Disk Configuration
  hosts: backup
  become: true
  tasks:
    - name: BACKUP CONFIG | Create partition
      parted:
        device: /dev/sdb
        number: 1
        state: present
      tags:
        - disk

    - name: BACKUP CONFIG | Create filesystem
      filesystem:
        fstype: ext4
        dev: /dev/sdb1
      tags:
        - disk

    - name: BACKUP CONFIG | Create mount point
      file:
        path: /var/backup
        state: directory
      tags: 
        - disk

    - name: BACKUP CONFIG | Mount disk
      mount:
        path: /var/backup
        src: /dev/sdb1
        state: mounted
        fstype: ext4
      tags: 
        - disk

    - name: BACKUP CONFIG | Change file ownership, group and permissions
      file:
        path: /var/backup
        owner: borg
        group: borg
      tags:
        - user

    - name: BACKUP CONFIG | Touch a file, /home/borg/.ssh/authorized_keys 
      file:
        path: /home/borg/.ssh/authorized_keys
        state: touch
        mode: u=rw,g-rwx,o-rwx
      tags:
        - user
        - ssh-config

    - name: BACKUP CONFIG | fill /home/borg/.ssh/authorized_keys 
      authorized_key:
        user: borg
        state: present
        key: "{{ lookup('file', '/tmp/id_ssh_rsa.pub') }}"
      tags:
        - ssh-config

#        fs_type: ext4

#    - name: NGINX | configure logging
#      lineinfile:
#        path: /etc/nginx/nginx.conf
#        insertafter: "{{ item.search }}"
#        line: "{{ item.after }}"
#      with_items: 
#        - { search: '\s*error_log.*', after: 'error_log syslog:server={{ log_vm_ip }}:514,tag=nginx_error;' }
#        - { search: '\s*access_log.*', after: 'access_log syslog:server={{ log_vm_ip }}:514,tag=nginx_access,severity=info combined;' }
#      notify:
#        - restart nginx
#      tags:
#        - nginx-package
#        - nginx-conf
#
#    - name: NGINX | Audit config changes
#      blockinfile:
#        path: /etc/audit/rules.d/audit.rules 
#        block: |
#          -w /etc/nginx/nginx.conf -p wa -k nginx_conf
#          -w /etc/nginx/default.d/ -p wa -k nginx_conf
#      notify:
#        - restart auditd
#      tags:
#        - auditd-conf
#
#    - name: AUDITD | Install audispd-plugins package
#      yum:
#        name: audispd-plugins
#        state: latest
#      tags:
#        - packages
#
#    - name: AUDITD | Edit config
#      lineinfile:
#        path: "{{ item.file }}"
#        regexp: "{{ item.search }}"
#        line: "{{ item.replace }}"
#      with_items: 
#        - { search: '^log_format = .*', replace: 'log_format = RAW', file: '/etc/audit/auditd.conf' }
#        - { search: '^name_format = .*', replace: 'name_format = HOSTNAME', file: '/etc/audit/auditd.conf' }
#        - { search: '^active = .*', replace: 'active = yes', file: '/etc/audisp/plugins.d/au-remote.conf' }
#        - { search: '^remote_server =.*', replace: 'remote_server = {{ log_vm_ip }}', file: '/etc/audisp/audisp-remote.conf' }
#      notify:
#        - restart auditd
#      tags:
#        - auditd-conf
#
#  handlers:
#    - name: restart nginx
#      systemd:
#        name: nginx
#        state: restarted
#        enabled: yes
#
#    - name: reload nginx
#      systemd:
#        name: nginx
#        state: reloaded
#
#    - name: restart auditd
#      command: /sbin/service auditd restart
#
#- name: CHRONYD | Tuning
#  hosts: all
#  become: true
#  tasks:
#    - name: CHRONYD | copy config file
#      copy:
#        src: /usr/share/zoneinfo/Europe/Moscow
#        dest: /etc/localtime
#        remote_src: true
#      notify:
#        - restart chronyd
#      tags:
#        - chronyd
#
#  handlers:
#    - name: restart chronyd
#      systemd:
#        name: chronyd
#        state: restarted
#        enabled: yes
#
#- name: LOG | Configuration
#  hosts: log
#  become: true
#  tasks:
#    - name: RSYSLOG | Edit config
#      replace:
#        path: /etc/rsyslog.conf
#        regexp: "{{ item }}"
#        replace: '\1'
#      loop:
#        - '^\s*#*\s*(\$ModLoad imudp.*)'
#        - '^\s*#*\s*(\$UDPServerRun 514.*)'
#        - '^\s*#*\s*(\$ModLoad imtcp.*)'
#        - '^\s*#*\s*(\$InputTCPServerRun 514.*)'
#      notify:
#        - restart rsyslog
#      tags:
#        - rsyslog
#
#    - name: RSYSLOG | Append config
#      blockinfile:
#        path: /etc/rsyslog.conf
#        block: |
#          $template RemoteLogs,"/var/log/rsyslog/%HOSTNAME%/%PROGRAMNAME%.log"
#          *.* ?RemoteLogs
#          & ~
#      notify:
#        - restart rsyslog
#      tags:
#        - rsyslog
#
#    - name: AUDITD | Edit config
#      replace:
#        path: /etc/audit/auditd.conf
#        regexp: '^\s*#*\s*(tcp_listen_port.*)'
#        replace: '\1'
#      notify:
#        - restart auditd
#      tags:
#        - auditd-conf
#
#  handlers:
#    - name: restart rsyslog
#      systemd:
#        name: rsyslog
#        state: restarted
#        enabled: yes
#
#    - name: restart auditd
#      command: /sbin/service auditd restart
